services:
  - type: web
    name: image-stitch-backend
    env: python
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn stitch:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: ALLOWED_ORIGINS
        value: "*"
